services:
  npf-app:
    image: docker.io/nfrastack/nginx-php-fpm/8.5-alpine
    container_name: npf-app
    labels:
      - traefik.enable=true
      - traefik.http.routers.npf.rule=Host(`npf.example.com`)
      - traefik.http.services.npf.loadbalancer.server.port=80
    volumes:
      - ./data/:/www/html
      - ./logs/:/logs
    environment:
      - TIMEZONE=America/Vancouver
    networks:
      - services
      - proxy
    restart: always

networks:
  proxy:
    external: true
  services:
    external: true

